name: Docker Release

on:
  release:
    types: [created]

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from config.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' config.yaml | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/clipper-server
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract metadata for Home Assistant Add-on
        id: ha-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/clipper-server-addon
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push standard Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Home Assistant add-on image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.ha-meta.outputs.tags }}
          labels: ${{ steps.ha-meta.outputs.labels }},io.hass.type=addon,io.hass.version=${{ steps.version.outputs.version }},io.hass.arch=all
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base:14.0.0 